### ISSUE TITLE
Possibility to call Analytics methods before AnalyticsBrowser.load and flush buffer after

### ISSUE THREAD

**Issue by willjosefi** [segmentio/analytics-next#374]
Hey everyone.

We are trying to use this library inside our project but we are seeing a situation. We need a way to start call analytics methods before the AnalyticsBrowser.load finishes.

We tried to instantiate Analytics and started to call the methods, which seems to be working.
But following the examples inside this repository README, which says to call Analytics.load and assign/merge the response results to the previous instantiated Analytics, doesn't seem to be dispatching the "queued" items

We did something like this:

```javascript
import { Analytics, AnalyticsBrowser } from '@segment/analytics-next'

const analytics = new Analytics({})

analytics.page('pagename')

AnalyticsBrowser.load({ writeKey: xxxxxx }).then(([response]) => {
  analytics = response
  // we tried Object.merge as well
  Object.assign(analytics, response)
})
```

The events dispatched after the .load are working. Only the previous ones are not being dispatched

Are we doing something wrong?
Should we implement our own "queue" and flush after the load()?

**Comment by pooyaj** [comment]
Hey @willjosefi, I think the queue-ing implementation requires a little bit of DIY, but here are some pointers: 
- We attempt to `flush` buffered events [here](https://github.com/segmentio/analytics-next/blob/master/src/browser.ts#L256) and [here](https://github.com/segmentio/analytics-next/blob/master/src/browser.ts#L230) but the buffer should conform to certain format
- In order to integrate with the native buffering logic, you need to create a buffer similar to the one created by Segment snippet ( https://github.com/segmentio/snippet/blob/master/template/snippet.js#L4-L62 ). Probably something like this will work: 
```
var analytics = (window.analytics = window.analytics || []);

analytics.methods = [
  'trackSubmit',
  'trackClick',
  'trackLink',
  'trackForm',
  'pageview',
  'identify',
  'reset',
  'group',
  'track',
  'ready',
  'alias',
  'debug',
  'page',
  'once',
  'off',
  'on',
  'addSourceMiddleware',
  'addIntegrationMiddleware',
  'setAnonymousId',
  'addDestinationMiddleware',
];

analytics.factory = function (method) {
  return function () {
    var args = Array.prototype.slice.call(arguments);
    args.unshift(method);
    analytics.push(args);
    return analytics;
  };
};

for (var i = 0; i < analytics.methods.length; i++) {
  var key = analytics.methods[i];
  analytics[key] = analytics.factory(key);
}
```

Then in your code do something like: 

```
import { Analytics, AnalyticsBrowser } from '@segment/analytics-next'

window.analytics.page('pagename')

AnalyticsBrowser.load({ writeKey: xxxxxx }).then(([response]) => {
  analytics = response
  // we tried Object.merge as well
  window.analytics = response
})
```

**Comment by willjosefi** [comment]
@pooyaj thank you very much for this explanation, it helped a lot our team and worked flawlessly
