### ISSUE TITLE
Error when registering an integration from segmentio/analytics.js-integrations

### ISSUE THREAD

**Issue by martymcflyDMC** [segmentio/analytics-next#408]
Trying to add some client-side plugins from "https://github.com/segmentio/analytics.js-integrations", and I am getting a callback error.

**Here is my implementation:**
```typescript
const analytics = new Analytics({
  writeKey: 'some-write-key'
})
import { Analytics } from '@segment/analytics-next'
import * as Amplitude from '@segmentio/analytics.js-integrations/integrations/amplitude'
const plugins: Plugin[] = []
const amplitude: Plugin = Amplitude({apiKey: 'my-api-key'})
plugins.push(amplitude)
analytics.register(...plugins)
analytics.initialize()
```

**Error:**
```bash
Uncaught TypeError: callback is not a function
```
It is trying to call a callback that does not exists in this code: 
```javascript
exports.load = function(name, locals, callback) {
  // Argument shuffling
  if (typeof name === 'function') { callback = name; locals = null; name = null; }
  if (name && typeof name === 'object') { callback = locals; locals = name; name = null; }
  if (typeof locals === 'function') { callback = locals; locals = null; }

  // Default arguments
  name = name || 'library';
  locals = locals || {};

  locals = this.locals(locals);
  var template = this.templates[name];
  if (!template) throw new Error(fmt('template "%s" not defined.', name));
  var attrs = render(template, locals);
  callback = callback || noop;
  var self = this;
  var el;

  switch (template.type) {
  case 'img':
    attrs.width = 1;
    attrs.height = 1;
    el = loadImage(attrs, callback);
    break;
  case 'script':
    el = loadScript(attrs, function(err) {
      if (!err) return callback();
      self.debug('error loading "%s" error="%s"', self.name, err);
    });
      // TODO: hack until refactoring load-script
    delete attrs.src;
    each(function(val, key) {
      el.setAttribute(key, val);
    }, attrs);
    break;
  case 'iframe':
    el = loadIframe(attrs, callback);
    break;
  default:
      // No default case
  }

  return el;
};
```

Is this not the correct way to implement integrations from "https://github.com/segmentio/analytics.js-integrations"?

**Comment by chrisradek** [comment]
@martymcflyDMC Thanks for opening this issue.

The integrations from `analytics.js-integrations` don't conform to the [Plugin](https://github.com/segmentio/analytics-next/blob/86ed4948916d2f37bfc037c32491f437ce47cd7f/src/core/plugin/index.ts#L14) interface. Both the `Plugin` interface and the integrations have a `load` method, but they accept different arguments. That's why you're getting the callback error - the library is attempting to call `load()` on a plugin but gets an integration instead.

Internally we have the [LegacyDestination](https://github.com/segmentio/analytics-next/blob/86ed4948916d2f37bfc037c32491f437ce47cd7f/src/plugins/ajs-destination/index.ts#L65) plugin that handles wrapping integrations but it expects to be loading an integration from the segment CDN.

Can you share more about why you're trying to load an integration directly rather than have the library load it based on the source settings? I don't believe we have an easy way to do what you want today but if we understand your use-case better we may be able to suggest an alternative or consider adding this functionality.

**Comment by cfey** [comment]
Hi,
I got a similar question
I want to use this open source library and one or two integrations from @segmentio/analytics.js-integrations
For using an standardized interface for tracking. Let's say I use HubSpot, FB Pixel and one custom Destination (own API).
How can I bundle these to get a standalone `.js` file or better to request the integrations and this library to be build into my project

Is this possible and if yes, how?

**Comment by chrisradek** [comment]
@cfey It's not currently possible to import integrations directly with this library. Right now you'd need to rely on analytics-next fetching those integrations based on your source configuration. We do want to support being able to import these integrations directly though. Marking as a feature request.

**Comment by cfey** [comment]
@chrisradek Hi, I wrote quite some time ago
Is this now possible?
It would be even possible if we could configure from which URL the integrations should be loaded

**Comment by chrisradek** [comment]
@cfey 
Yes, you can now load integrations from npm.
Check out the docs here and please let us know if anything is unclear!
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#add-destinations-from-npm
