### ISSUE TITLE
Timeout not working

### ISSUE THREAD

**Issue by lukebussey** [segmentio/analytics-next#409]
I cloned this repository and started up the local dev environment for testing events.

I updated the track event to output the default timeout setting and add timing events to the console:
```js
    // @ts-ignore
    console.log(analytics.settings)
    console.time('track')
    const ctx = await analytics.track(evt?.event ?? 'Track Event', evt)
    console.timeEnd('track')
```
analytics.settings.timeout is set to the default 300ms, but the track call returns after 60ms:

`track: 59.259765625 ms`

If I add a callback to the track call, the time is essentially the same:

`const ctx = await analytics.track(evt?.event ?? 'Track Event', evt, null, () => { console.timeLog('track')})`

I also don't have any luck changing the timeout with `window.analytics.timeout(1000)` or passing it into `AnalyticsBrowser.load`

Is setting the default timeout supported?

**Comment by chrisradek** [comment]
@lukebussey Thanks for filing this issue! I've got to dig into the intent of `timeout` but it looks like it currently:
- is used for trackLink/trackForm to set a timeout for sending events to segment before navigating away from the page
- is used as the max amount of time the callback passed to an API like `track` can take.
  - For example, if your callback to track was async and took longer than the `timeout` specified, the library would stop waiting for the callback to resolve and you'd see a 'callback error' in the logs.

It doesn't look like it currently applies to the actual HTTP requests to segment/destinations.

Can you share what behaviour you're looking to control using timeout?

**Comment by lukebussey** [comment]
I was expecting the same behavior as in in Analytics.JS v1. The timeout would be the length of time before a callback returns, allowing for and third party tracking to complete. E.g.

```
analytics.track('Event', {
 foo: 'bar'
}, function(){
  window.location.href = "https://www.example.com/"
});
```

In that example, the page wouldn't navigate away until the default timeout duration has passed.

https://github.com/segmentio/analytics.js-core/blob/da691296b4a184271f85677962fc19741988c0f3/lib/analytics.ts#L734

**Comment by chrisradek** [comment]
@lukebussey Thanks for the clarification - I'm still getting up to speed on Analytics.JS v1 myself!

A major difference between analytics-next and analytics.js v1 is that with analytics-next the event APIs return a promise that resolves once the event has been sent to destinations. The 2 caveats for this are:
1. If the user is offline, then it resolves when the event is stored in localstorage.
2. If the library hasn't been loaded yet, then these APIs return void.

So, writing `analytics.track('Event', {}).then(() => window.location.href = "https://www.example.com/")` will wait for the event to be sent before navigating away from the page. This is different from analytics.js v1 where it was harder to know if/when an event was sent to all destinations.

With that in mind, I suspect the timeout is no longer placed before the callback because now you know it's safe to navigate by waiting for the promise to resolve, rather than trying to give the library some time to get the events out.

Now that I'm thinking through this, it is possible that even though we've sent an event to a 3rd party destination, if it is a client-side destination that has its own delay (maybe it does its own batching for example) then the library wouldn't know about that and you could end up navigating away early. Is this the sort of scenario you're running into?

**Comment by aecorredor** [comment]
Commenting on this closed issue since I'm running into a similar issue even on the latest next-analytics version. I'm trying to track a "checkout started" event which occurs when a user presses a checkout button that navigates to an external checkout flow hosted on shopify. I'm attempting to use the callback to send the event before navigating away from the page, but the event is not being recorded. As a workaround, we hijacked the button and instead of using the callback we're using the onClick to first call `track` and then call `setTimeout` to actually do the redirect after 300ms. We do see events come through this way, but it doesn't seem to be reliable; i.e. we don't always see the events come through.

**Comment by aecorredor** [comment]
Just bumping this up. We tried to use the native timeout to correctly track events right before navigating away from the page, but still didn't see those events come through. 

As far as our custom solution, sometimes 200ms (and even 300ms) doesn't seem to be enough for the event to go through.

**Comment by aecorredor** [comment]
Coming back to this, I just probably had a bad setup all along...I was using the `@segment/snippet` package and not `analytics-next`. I'll let you guys know if everything works after upgrading.

**Comment by jony1993** [comment]
@aecorredor 
We have the same problem...
Have you solved it already for your project?

**Comment by aecorredor** [comment]
> @aecorredor 
> 
> We have the same problem...
> 
> Have you solved it already for your project?

I actually had an error: I was using the snippet package and not this one. After I switched, the problem went away. I think you could still get around it by implementing your own setTimeout before navigating away.
