### ISSUE TITLE
Different options for handling failure to acquire lock

### ISSUE THREAD

**Issue by HarrisonB** [segmentio/analytics-next#438]
Hello,

While using this library, we occasionally get some clients who are unable to acquire a lock, [raising an error in the process](https://github.com/segmentio/analytics-next/blob/1ace0f334848e57df9a128b51f02ce6c4bdfb123/src/lib/priority-queue/persisted.ts#L84). It's unclear to me as a developer what to do about this. It's only occurring rarely so I'm not concerned about a widespread gap in tracking, but it feels like something that should be logged rather than raised all the way to the window's error handler. There do appear to be some `catch`es in the same file around some other calls to `mutex` so maybe this was the original intention?

**Comment by chrisradek** [comment]
@HarrisonB Thanks for logging this issue.

You're right - and if `mutex` is called inside of its `setTimeout` you won't even be able to catch the error. I suspect that was the intention but since it is uncatchable anyway we should be logging.

As far as what might trigger this - I think it would require multiple browser tabs loading the same domain simultaneously which could cause contention to claim a lock. Alternatively, if a user had multiple tabs pointing at your source and closed the browser, that would trigger each tab to try to get the lock so they can save any pending events.

For the latter scenario, we're considering listening to visibility changes instead of `beforeunload`, so that should help reduce contention.
