### ISSUE TITLE
Using .ready() to set state

### ISSUE THREAD

**Issue by martyjg** [segmentio/analytics-next#466]
Hi, I want to use analytic's user/anonymous ID in combination with another A/B testing tool. I want to take the user ID from analytics when it is ready and then update the UI with a state change. I have something like this:

```
async function loadAnalytics() { 
  const [ analytics, context ] = await AnalyticsBrowser.load({ writeKey: 'e4tHcwj8okR871fG0eK5pm58sxijbxjS' }) 
  analytics.ready(() => {
    console.log(window.analytics.user().anonymousId())
  })  
  return analytics 
}
```

I'm calling this inside a component:
```
useEffect(() => {
  loadAnalytics()
}, [])
```

But it errors as such:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'user')`

Am I using .ready() incorrectly? I don't know how else to reliably get the anonymous ID.
I also need to work out how to set the state from there.

**Comment by chrisradek** [comment]
@martyjg Thanks for opening this issue!

Unless you're including the analytics snippet on your page, `window.analytics` will be undefined. Based on your sample you should be able to just call the analytics object returned by `AnalyticsBrowser.load` directly.

Also since you're awaiting `AnalyticsBrowser.load()`, you don't actually need to call `.ready()` - `.load()` will resolve after plugins have been registered and the library has finished initializing.

**Comment by martyjg** [comment]
@chrisradek Amazing, thank you!
