### ISSUE TITLE
window._cio.page is not a function

### ISSUE THREAD

**Issue by cristhian-bento** [segmentio/analytics-next#736]
We started getting the error in production like 3 weeks ago, and it is constantly failing, mostly for Apple devices using Safari/Safari Mobile.
The sentry logs show the error comes from customer IO integration.

<img width="915" alt="image" src="https://user-images.githubusercontent.com/103455424/209218456-2ee007d4-8283-4f12-bbb0-bc03d973287a.png">

What should we do to fix it? Is there any workaround?

We are using Analyticsjs 2.0.

Thanks!

**Comment by silesky** [comment]
@cristhian-bento. I think https://github.com/segmentio/action-destinations/issues would be a more appropriate place for this issue!

**Comment by cristhian-bento** [comment]
Thanks, @silesky! Closing this...

**Comment by zikaari** [comment]
This is an issue with CustomerIO's `track.js` script.

In that script there is a call to the `EventTarget` constructor using the `new` keyword, Safari 13 and below do not support `EventTarget` being constructed using the `new` keyword. The script errors out, and prevents initialization of the library, thus leading to the error that you see in Sentry.

This can be fixed by adding a `EventTarget` polyfill **before** the analytics snippet so everything is ready by the time CustomerIO script executes.
