### ISSUE TITLE
@segment/analytics-node won't build in Vercel Edge -- Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime

### ISSUE THREAD

**Issue by jedashford** [segmentio/analytics-next#874]
We installed @segment/analytics-node in our nextjs project and vercel failed to build the project with the below error.  We're using the most recent version of the library. 
`"@segment/analytics-node": "1.0.0-beta.26",`

```
./node_modules/@segment/analytics-core/dist/esm/utils/group-by.js
--
10:13:52.344 | Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime
10:13:52.345 | Used by groupBy
10:13:52.345 |  
10:13:52.345 | Import trace for requested module:
10:13:52.345 | ./node_modules/@segment/analytics-core/dist/esm/queue/event-queue.js
10:13:52.345 | ./node_modules/@segment/analytics-core/dist/esm/index.js
10:13:52.345 | ./node_modules/@segment/analytics-node/dist/esm/app/analytics-node.js
10:13:52.345 | ./node_modules/@segment/analytics-node/dist/esm/index.js
10:13:52.345 | ./src/utils/SegmentNode.ts
10:13:52.345 | ./middleware.ts
```

**Comment by jedashford** [comment]
This seems to be NextJS version specific. I get the error on `"next": "12.2.4"`  but NOT on `"next": "13.4.5"`

**Comment by silesky** [comment]
Thanks for taking out an issue.

Yep, NextJS's SWR compiler has definitely come a long way since 13. They acknowledged that since, in 12, it was flagged under "experimental".

Since you were able to resolve it in more recent versions of next, and 13 has been out for quite a while, I don't think we're going to take any action at this time.
