### ISSUE TITLE
Unable to resolve modules on latest Expo with Metro web

### ISSUE THREAD

**Issue by ocho-cesar** [segmentio/analytics-next#881]
When trying to build my react-native app with the latest metro web bundler using Expo, I get the next error

``` bash
> Unable to resolve "@lukeed/uuid" from "node_modules/@segment/analytics-next/dist/pkg/core/events/index.js"
```
Possibly related to https://github.com/aws-amplify/amplify-js/issues/11474

**Comment by silesky** [comment]
@ocho-cesar. Hey, this isn't a react native package -- please use https://github.com/segmentio/analytics-react-native.

**Comment by ocho-cesar** [comment]
@silesky yes, it was working before it. And was opening this here because I was running expo in the web environment, that is no react-native (hermes) runtime, but a web environment using metro as the bundler.

**Comment by Jackman3005** [comment]
Hi @silesky , it would be great to re-open this issue. 

I too receive the exact same error message @ocho-cesar is receiving when trying to use the metro bundler for Web. 

We cannot switch to the package you mentioned because `analytics-react-native` does not yet support Web as discussed [in this issue](https://github.com/segmentio/analytics-react-native/issues/455) which is over a year old.

Those of us using Segment are forced to include both libraries and use the correct one based on the current platform. Which has been just fine for us for quite some time on both mobile and web in production. Albeit with the webpack bundler, not the metro bundler. 

There seems to be some issue with the combination of the Metro bundler for RN Web and this import from `@segmentio/analytics-next`

**Comment by Jackman3005** [comment]
I tried commenting out all the Analytics code to see if it was the only error I'm receiving when trying to bundle for RN Web using Metro. It was not, I was also receiving the same error noted [in this issue](https://github.com/react-native-maps/react-native-maps/issues/4641) with `react-native-maps`.  I was able to temporarily "patch" that problem with the fix mentioned in the issue and can confirm that I am able to bundle for RN Web with metro after that.

That being the case, I think this issue does deserve to be on the Segment side and I suspect it should be solvable with the hints in the `react-native-maps` issue linked and the issues it links to.

For context, we have 108 Dependencies in our project, and only two were causing issues when trying to bundle with metro.

**Comment by silesky** [comment]
@Jackman3005 This worked previously and then expo updated and it broke, while continuing to work on all other tested bundlers... so this is 1000% a problem with the new react native expo bundler.

 Did you explore their PR issues? I saw this: https://github.com/facebook/metro/issues/1003

**Comment by Jackman3005** [comment]
Hi @silesky Thanks for the detailed message. Now that I understand it better, I am inclined to agree with you. I will give the fix a try and continue the conversation on the metro bundler side.

**Comment by jparksecurity** [comment]
@silesky Hi, Sorry for pinging you on the closed issue.

I think the issue is that `Metro` uses a `module` entry instead of `main`. Would adding `react-native` in `package.json` be something Segment can take a look at?

I opened an issue in Expo to discuss this closed issue.

And one thing the Expo team member mentioned was

> Preferably, if Segment is willing to make it work out of the box for React Native, they should add a react-native field with the CJS version of the package. That should get picked up properly by Metro.

My issue in Expo: https://github.com/expo/expo/issues/27902#issuecomment-2031963082
