### ISSUE TITLE
Segment broke with next js 13.5.2

### ISSUE THREAD

**Issue by AbdelrhmanX7** [segmentio/analytics-next#969]
i got this issue while i am using yarn build with next js 13.5.2
![image](https://github.com/segmentio/analytics-next/assets/74682593/4bd6354f-a47b-4604-819e-873b25ce8a5a)

**Comment by silesky** [comment]
Thanks for opening an issue @AbdelrhmanX7 

 It looks like you're calling a .track() in a server environment: please ensure you only call it in the browser. 
 
 ```
 const analytics = new AnalyticsBrowser() // works on the server without breaking
analytics.load({...}) // don't do this, but this works on the server without throwing an error
analytics.track() // this will break
 ```

**Comment by silesky** [comment]
"document is not defined" means that it's being called in a server context. Please see those next.js examples.

Older versions of this library may have seemed like they worked because they didn't cause your app to explode, but calling track in a server context is never we allow and can even be dangerous if it can result in fatal unhandled promises that could even crash future node app inadvertently.
